- label: cat_cols_fewer_than_20_distinct
  n_cols: 
    greater_than: 1
  conditions_all:
    hdType:
      equals: Cat
    n_distinct:
      less_than: 20



- label: cat_cols_fewer_than_20_distinct
  requirements: true
  conditions:
    hdType_equals_Cat: true
    n_distinct_less_than_20: true