description: Sankey chart
table: 
  sankey_data:
    table_id: sankey_data
    specs: 
      n_cols:
        greater_than: 1
      n_rows:
        greater_than: 0
      frType: 
        contains: "Cat-Cat"
    fields:
      col_max_cat:
        field_id: col_max_cat
        specs:
          hdType: Cat
          n_unique:
            less_than: 20
          label: Sankey data
          n_cols: 
            greater_than: 1
